apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-maven-settings
  namespace: devops-jenkins
data:
  settings.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
             xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
      <mirrors>
        <mirror>
          <id>central</id>
          <name>central</name>
          <mirrorOf>central</mirrorOf>
          <url>https://repo1.maven.org/maven2/</url>
        </mirror>
        <mirror>
          <id>nexus-aliyun</id>
          <mirrorOf>central</mirrorOf>
          <name>Nexus aliyun</name>
          <url>https://maven.aliyun.com/repository/public</url>
        </mirror>
        <mirror>
          <id>mirror</id>
          <mirrorOf>!rdc-releases,!rdc-snapshots</mirrorOf>
          <name>mirror</name>
          <url>https://maven.aliyun.com/nexus/content/groups/public</url>
        </mirror>
      </mirrors>
    </settings>